py_library(
  name = "helper_library",
  data = [
    'cmd_exec.py',
    'docker_image.py',
    'docker_volume.py',
    'job_control_loader.py',
    '//:api',
  ],
  visibility = ["//visibility:public"],
)
