load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")
load("@bazel_gazelle//:def.bzl", "gazelle")

# gazelle:prefix github.com/envoyproxy/envoy-perf/salvo-remote
gazelle(name = "gazelle")

