package(default_visibility = ["//visibility:public"])

load("@envoy_api//bazel:api_build_system.bzl", "api_proto_library")

api_proto_library(
    name = "response_options_proto",
    srcs = ["response_options.proto"],
)
