parameters:
- name: ciTarget
  displayName: "CI target"
  type: string
  default: "build"
- name: repo
  displayName: "repository"
  type: string
  default: ""

steps:
- bash: |
    echo "disk space at beginning of build:"
    df -h
  displayName: "Check disk space at beginning"

- script: "${{ parameters.repo }}/ci/run_envoy_docker.sh ${{ parameters.repo }}/ci/do_ci.sh ${{ parameters.ciTarget }}"
  workingDirectory: $(Build.SourcesDirectory)
  displayName: "CI script in ${{ parameters.repo }"
  env:
    BAZEL_REMOTE_CACHE: $(LocalBuildCache)

- bash: |
    echo "disk space at end of build:"
    df -h
    # Cleanup offending files with unicode names
    rm -rf $(Build.StagingDirectory)/tmp/*/*/external/go_sdk/test/fixedbugs
  displayName: "Check disk space at end"
  condition: always()

# Publish the binaries as artifacts.
- ${{ if eq(parameters.repo, 'nighthawk') }}:
  - task: PublishPipelineArtifact@1
    displayName: "Publish Nighthawk client"
    inputs:
      targetPath: "$(Build.SourcesDirectory)/nighthawk/bazel-bin/nighthawk_client"
      artifactName: "Nighthawk client"
  - task: PublishPipelineArtifact@1
    displayName: "Publish Nighthawk test server"
    inputs:
      targetPath: "$(Build.SourcesDirectory)/nighthawk/bazel-bin/nighthawk_test_server"
      artifactName: "Nighthawk test server"
