# Initial pipeline for Salvo MVP.
#
# MVP doc:  https://docs.google.com/document/d/15auKcxLfw8iILL7EF4tJ8VrnHce6KiZvd9tzWweT0DY/edit
# Design: https://docs.google.com/document/d/1Qfueli357u4QgOb-7-8RL98N0XnMeu2k6VJDoUwN0A4/edit?resourcekey=0-AyeFMQHHiuajx8JK2w_yfA
# Pivot to direct VM: https://docs.google.com/document/d/1auXzV-AEXgMzbtdG06XlZ2d9X5l_XadMheA9h51E7yc/edit
# AZP docs: https://learn.microsoft.com/en-us/azure/devops/pipelines/?view=azure-devops

# Salvo builds the Nighthawk (load generator), The Envoy (system under test)
# and the Nighthawk test server (the fake backend).
#
# Pipeline variable usePreviousBuildId is used for debugging.
#   - When set to an empty value, all components are built, ASG is pre-heated,
#     salvo-remote is executed with the built components and the ASG is cooled
#     down.
#   - When set to an AZP pipeline build ID, component building, pre-heating and
#     cooling down is skipped. Salvo-remote gets executed with components built
#     in a previous pipeline execution identified by the value if
#     usePreviousBuildId.
resources:
  repositories:
    - repository: "nighthawk"
      type: "github"
      endpoint: "GitHub - mum4k - Salvo MVP"
      name: "envoyproxy/nighthawk"
    - repository: "envoy"
      type: "github"
      endpoint: "GitHub - mum4k - Salvo MVP"
      name: "envoyproxy/envoy"

stages:
- stage: "build_components"
  dependsOn: []
  condition: eq(variables.usePreviousBuildId, '')
  pool: "envoy-x64-large"
  jobs:
  - job: "build_components"
    displayName: "Build components"
    timeoutInMinutes: 120
    steps:
    - checkout: "nighthawk"
    - checkout: "envoy"
    - checkout: "self"
    - template: "bazel.yml"
      parameters:
        rbe: false
        repo: "nighthawk"
        ciTarget: "opt_build"
    - template: "bazel.yml"
      parameters:
        rbe: true
        repo: "envoy"
        ciTarget: "bazel.release.server_only"

- stage: "build_amis"
  dependsOn: ["build_components"]
  condition: eq(variables.usePreviousBuildId, '')
  pool:
    vmImage: "ubuntu-22.04"
  jobs:
  - job: "build_amis"
    displayName: "Build VM AMIs"
    timeoutInMinutes: 120
    steps:
    - template: "ami_builder.yml"
      parameters:
        repo: "nighthawk"
        ciTarget: "opt_build"

- stage: "build_salvo_remote"
  dependsOn: []
  condition: eq(variables.usePreviousBuildId, '')
  pool: "envoy-x64-large"
  jobs:
  - job: "build_salvo_remote"
    displayName: "Build salvo-remote"
    timeoutInMinutes: 120
    steps:
    - checkout: "nighthawk"
    - checkout: "self"
    - template: "bazel.yml"
      parameters:
        rbe: false
        repo: "envoy-perf"
        ciTarget: "package_salvo_remote_and_sandboxes"

- stage: "preheat_salvo_asg"
  dependsOn: []
  condition: eq(variables.usePreviousBuildId, '')
  pool: "envoy-x64-large"
  jobs:
  - job: "preheat_salvo_asg"
    displayName: "Preheat the salvo-control ASG"
    timeoutInMinutes: 120
    steps:
    - checkout: "nighthawk"
    - checkout: "self"
    - template: "salvo_controller.yml"
      parameters:
        action: "preheat"

- stage: "run_salvo_remote"
  dependsOn: ["build_amis", "build_salvo_remote", "preheat_salvo_asg"]
  condition: always()
  pool: "salvo-control"
  jobs:
  - job: "run_salvo_remote"
    displayName: "Run salvo-remote"
    timeoutInMinutes: 120
    steps:
    - checkout: "nighthawk"
    - checkout: "self"
    - template: "salvo_controller.yml"
      parameters:
        action: "run"
        usePreviousBuildId: "$(usePreviousBuildId)"

- stage: "cooldown_salvo_asg"
  dependsOn: ["run_salvo_remote"]
  condition: eq(variables.usePreviousBuildId, '')
  pool: "envoy-x64-large"
  jobs:
  - job: "cooldown_salvo_asg"
    displayName: "Cooldown the salvo-control ASG"
    timeoutInMinutes: 120
    steps:
    - checkout: "nighthawk"
    - checkout: "self"
    - template: "salvo_controller.yml"
      parameters:
        action: "cooldown"
