trigger:
  branches:
    include:
    - "main"

stages:
- stage: check
  dependsOn: []
  pool: "x64-large"
  jobs:
  - job: build_and_format
    displayName: "do_ci.sh"
    dependsOn: []
    strategy:
      maxParallel: 2
      matrix:
        #build:
        #  CI_TARGET: "build"
        format:
          CI_TARGET: "check_format"
    timeoutInMinutes: 120
    steps:
    - template: bazel.yml
      parameters:
        ciTarget: $(CI_TARGET)

#- stage: test
#  dependsOn: ["check"]
#  pool: "x64-large"
#  jobs:
#  - job: test
#    displayName: "do_ci.sh"
#    dependsOn: []
#    strategy:
#      maxParallel: 1
#      matrix:
#        test:
#          CI_TARGET: "test"
#    timeoutInMinutes: 120
#    steps:
#    - template: bazel.yml
#      parameters:
#        ciTarget: $(CI_TARGET)
#
#- stage: coverage
#  dependsOn: ["test"]
#  pool: "x64-large"
#  jobs:
#  - job: coverage
#    displayName: "do_ci.sh"
#    dependsOn: []
#    strategy:
#      maxParallel: 1
#      matrix:
#        coverage:
#          CI_TARGET: "coverage"
#    timeoutInMinutes: 120
#    steps:
#    - template: bazel.yml
#      parameters:
#        ciTarget: $(CI_TARGET)
#    - task: PublishPipelineArtifact@1
#      condition: always()
#      displayName: 'Publish the line coverage report'
#      inputs:
#        targetPath: $(System.DefaultWorkingDirectory)/salvo/coverage/html.zip
#        artifactName: CoverageReport
